=== hinantin/AshaninkaLexicon/treebanks/parallel_texts.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.1">
    <xs:simpleType name="language">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prq">
                <xs:annotation>
                    <xs:documentation>
                        ES: Asheninka del Peren√©.
                        EN: Perene Asheninka
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cni"/>
            <xs:enumeration value="es"/>
            <xs:enumeration value="en"/>
            <xs:enumeration value="pt"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="parallel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sentence" minOccurs="2" maxOccurs="6">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="language" name="lang" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <!-- 
                            <xs:element name="prq" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="es" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="en" minOccurs="1" maxOccurs="1"/>
                            -->
                            <xs:element name="morphology" minOccurs="1" maxOccurs="1" nillable="false">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="parsing" minOccurs="1" maxOccurs="1" nillable="false">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20190305_notempodoverao.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="0">
        <sentence lang="cpb">ASHI OSARẼTSIPAITEKI</sentence>
        <sentence lang="pt">NO TEMPO DO VERÃO</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1">
        <sentence lang="cpb">ISAIKI ASHENĨKAPAINI
OTHAPIYAKIINI AMÕYANI OITA
AWAIRO NÃPITSI APIWTXA.</sentence>
        <sentence lang="pt">OS ASHANINKA DAQUI VIVEM NA BEIRINHA
DO BRASIL, ÀS MARGENS DO RIO AMÔNIA,
NUMA ALDEIA CHAMADA APIWTXA.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2">
        <sentence lang="cpb">OSARẼTSI PAITEKI EẼTXERIKI
EERO IKIYAANAI ISHIKOIRAKI,
HATANAKI RANASHIWAITXA
ITSIPATXAARI ISHENĨKA PAINI,
IKOWIR IYOTERI.</sentence>
        <sentence lang="pt">NO TEMPO DO VERÃO AS CRIANÇAS
NÃO VÃO À ESCOLA. ANDAM COM SEUS
PARENTES PARA APRENDER COM ELES
AS COISAS QUE VÃO PRECISAR SABER
QUANDO CRESCEREM.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="3">
        <sentence lang="cpb">IYAATSI TAYRI ITXARINI, IKOWAKOTERI
        IYOTÃTXAAWORI RÃTERO TXEKOPI:
        EEROKA OTSIMATXE PIYOTERI PITOTERI ISHIWÃKI
        KAMETHA PIYOMATAKAIRO TXEKOPI. KAPIROKOTA
        EERO ITSIMÃTAWO TSIMERI. IKÃTSI IRIRORI.</sentence>
        <sentence lang="pt">TAYRI VAI VISITAR O SEU AVÔ PARA
        APRENDER A FAZER FLECHA:
        "VOCÊ TÊM QUE CORTAR AS PENAS IGUALZINHO.
        FLECHA COM PONTA DE TABOCA
        A CAÇA NÃO RESISTE!" - DIZ ELE.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="4">
        <sentence lang="cpb">IYAATATXE ITSIPATXARI IRẼTSI PIYÃKO
        EEHATSI IRITSIRO BIANCA, ROYAATANAKIRI
        RAKATXAATE IKÕKIRI WEWITO.
        HO! PAMINERITXA ETSĨYAKI, IKOWAKI
        IYAATE EEHATSI IRIRORI!</sentence>
        <sentence lang="pt">ELE VAI PARTIR COM SEUS IRMÃOS,
        PIANKO E BIANCA, E SEU TIO WEWITO,
        PARA UMA PESCARIA.
        EI! PARACE QUE ETSIYAKI, O CACHORRO,
        TAMBÉM QUER IR!</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="5">
        <sentence lang="cpb">AREETAPAKIYA HÃTA, OTSIMATXE ÃTAPAAKI
        APÃKOSHI AMÃTXAARI, EẼTAATSI TAYRI
        EEHATSI PIYÃKO RAMITAKOTSIRI IKÕKIRI
        IRIRORI, IROORI BIANCA ÃTATSI
        IPÃKOSHI OTXAPANITE.</sentence>
        <sentence lang="pt">CHEGANDO LÁ É PRECISO CONSTRUIR
        UMA CABANA PARA PASSAR A NOITE.
        ENQUANTO TAYRI E PIANKO AJUDAM
        SEU TIO BIANCA FAZ COM SUAS PRIMAS
        UMA CABANA PARA O PINTINHO.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="6">
        <sentence lang="cpb">IKITEESHITAKOMANAI, TAYRI
        ANANIKAKI IYOTAIRO IRITSIRO HĨPE
        IKÃTAITSIRO, OOSHERO PAÃPARI
        OTSIMATXE AMINERO KAMETHA.
        PISHAYE KANIRI ANANTXA, IRIRORI
        SHIRÃPARI PAINIRÃTE IYẼTAAMẼTO:
        IRÕYAKA OITEESHIRITE OMANAATE!</sentence>
        <sentence lang="pt">NO DIA SEGUINTE BEM CEDO TAYRI
        ENSINA OS IRMÃOS:
        "PARA O FOGO PEGAR É PRECISO
        FAZER COM CARINHO..."
        ANANTXA DESCASCA A MACAXEIRA E OS
        MENINOS PREPARAM SEUS ARPÕES:
        É DIA DE PESCARIA!</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="7">
        <sentence lang="cpb">HĨYAAKI ĨTHOMOITA ARI ISAIKI
        OIRÕTSI, ATSIKAWETAKARI IKIRIKI,
        KÃTSIMAITXA RAAKIRI EẼTXERIKI
        ITSITOKAIYAKIRINI.</sentence>
        <sentence lang="pt">NO FUNDO DO RIO UM CARANGUEJO
        QUASE LHES BELISCA O NARIZ, MAS
        OS MENINOS CONSEGUEM APANHÁ-LO.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="">
        <sentence lang="cpb">HĨPE IKAATSIKA PAAKARI
SHIMA? ARI IKAATSI APITE?
PIKÃTERI WEWITO ARIRIKA
PIMÕKAATAKA, TEKAATSIMA PIINA.
- IKÃTSI TAYRI.</sentence>
        <sentence lang="pt">- "QUANTOS PEIXES VOCÊ PESCOU?"
SÓ DOIS” – PERGUNTA TIO WEWITO
“AH JÁ DÁ PRA VOCÊ COMER”.
-“DÁ SIM, VOCÊ NÃO TEM MULHER”.
-COMPLETA TAYRI</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">
            

hĩpe	[=hĩpe][IndfSpecifCPB][=where; who]

kaatsika	[=kara~kaa][VRoot:CPB][=COP.CAP (EN: the.amount,, to.be.Nº/#.in.number/quantity_of_sth.)][--][&lt;*-ts][+EP]ts[--][-e~i+fut.+RSS@00000][MODALITY][+IRR]i[--][=ka][+Q]

paakari	[p-][VPers][2S/A+][--][=a][VRoot][=to.get][--][-ak][ASP][+PRF]ak[--][-a][+REAL]a[--][=ri][+3m.O]

shima	[=shima+m.+poss@ni.][NRoot][=fish; fish.sp., boquichico-fish (ES: boquichico, chupadora; sci.nm.: prochilodus.nigricans)]

?	?[$.]

ari	[=ari][PostPol][=PP][=there; so; thus; thereby; just.like.that (ES: así.es); to.be.this.way (ES: ser.así)]

ikaatsi	[i-][VPers][3m.S/A+][--][=kara~kaa][VRoot:CPB][=COP.CAP (EN: the.amount,, to.be.Nº/#.in.number/quantity_of_sth.)][--][&lt;*-ts][+EP]ts[--][-e~i+fut.+RSS@00000][MODALITY][+IRR]i

apite	[=apite][NumeralPRQ][=two]

?	?[$.]

pikãteri	[pi-][VPers][2S/A+][--][=kãt][VRoot][=to.say; to.call;; to.do; to.happen;; to.be (ES: ser); to.be.able][--][-e][+REAL]e[--][=ri][+3m.O]

wewito	[=vevito][NRoot][=person's.name]

aririka	[=ari][PostPol][=PP][--][=rika][+COND]::[=when (temporal.simultaneity), if (expresses.possible.condition)]

pimõkaataka	[pi-][VPers][2S/A+][--][=monkaa][VRoot][=to.measure; to.fulfill][--][-t][+EP]t[--][-ak][ASP][+PRF]ak[--][-a][+REAL]a

,	,[$.]

tekaatsima	[=tekaatsi][NRoot][=none, empty, zero, null][--][-ma][+DUB]

piina	[p-][NPers][2poss+][--][=iina+n.m.+inal@tsi.][NRoot][=mother; wife (kin.of.a.fe/male)]

.	.[$.]

-	-[$.]

ikãtsi	[i-][VPers][3m.S/A+][--][=kant][VRoot][=to.say; to.call;; to.do; to.happen;; to.be (ES: ser); to.be.able][--][-i][+REAL]i

tayri	[=tairi+n.m.][NRoot][=yellow-flowered.tree.sp. (ES: oropel; sci.nm.: erithrina.uley?)]

.	.[$.]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180623_mihasanaani11.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="1.0">
        <sentence lang="prq">APIINKA</sentence>
        <sentence lang="es">EL SUCESOR DE INCA</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully"/>
    </text>
    <text id="1.1">
        <sentence lang="prq">Sheeteni akarajetaiyeni maaroni nosaikajetzika.</sentence>
        <sentence lang="es">Buenas tardes a todos los que nos encontramos en este lugar.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.2">
        <sentence lang="prq">Iroñaaka sheetenika nonkinkitsatakoteri aparoni ashaninka ikantaitziri Apiinka.</sentence>
        <sentence lang="es">Ahora en esta tarde, voy a contarles sobre una persona llamada Apiinka.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.3">
        <sentence lang="prq">Saikaintsirika aka anampikika paitachari Metaroki.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.4">
        <sentence lang="prq">Iroñaaka ikantajiro virakocha Metraro.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.5">
        <sentence lang="prq">Yoka ashaninka osheki yaaki atziri, osheki yaaki atzirive.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.6">
        <sentence lang="prq">Yapototakiri, yapotojetakiri maaroni okanta yantavaitakantyaariri.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.7">
        <sentence lang="prq">Ari okantavitaka kameetsa, yantavaitakakiri, ipankitakakiri ishinkini, imachakite, iyaniri, ivaryantzitepaye, iyokani, irinkini.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.8">
        <sentence lang="prq">Osheki ipankitakajetakiri atziripaye arika yante ovantsi.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.9">
        <sentence lang="prq">Ityaankiri aparopaye: “Aviroka antatsini ovantsi, aviroka jatatsini antamiki, pamini vatsatsi avyari.”</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.10">
        <sentence lang="prq">Ari okantajetakari, kooyapaye iroo kotsivaitatsini, eentsipaye ontzimatye yamitakoteri irora inkoyavaite.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.11">
        <sentence lang="prq">Ikanta iyoka Apiinkaka osheki inintavitakari, poñaashitaka avisaki osheki osarentsi.</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180828_suarezhistorias04.xml
<!-- 

@book{suarez:historias:04,
author={Su\'{a}rez Sebasti\'{a}n, Amanda and Pilares Casas, Guido and Vargas, Lita},
title={Historias Ash\'{a}ninkas para estar despiertos contadas e ilustradas por ni\~{n}as y ni\~{n}os de San Miguel de Marankiari, La Merced, Junin},
year={2004},
}

historiasashaninkas_free.pdf

-->
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="2.0">
        <sentence lang="prq">INCHATO TSOMONTE</sentence>
        <sentence lang="es">EL ARBOL BARRIGÓN</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2.1">
        <sentence lang="prq">Inchatotsomonte irointi antaro timatsiri ojempeki isaikantari kamintsi.</sentence>
        <sentence lang="es">El árbol barrigón es un árbol tremendo pues, tiene su ramas, tiene su duende.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2.2">
        <sentence lang="prq">Iro kantaincha te inkisajia kamintsi yanitapininti anta tomirimashiki, irocha eiro akempejitari, arika okompitakiami inchatotsomonte “¿Ari inkonijatitimotakemi maranke?”. Inkarate 10 antarotsa, arika, onkisakia inchatotsomonte ari inkonijatake irijaniki atiri meeka ontimatiye aya eirorika pobatsi ari inkajemakemi kamintsi, inkajemakemi irosati pikishotantanakia eiro panitajitsi ari pisabike irosati yobantakiami.</sentence>
        <sentence lang="es">Los árboles que tenemos aquí tienen su duende pero ya están amansados.
Allá en el monte, no te puedes acercar. Te aparece culebras, de 10 metros, que te comienza a rugir. Si estás solo, también se te aparece un ser, chiquitito nomás, un ser humano. Entonces te tienes que replegar porque si no te repliegas te comienza a llamar y te hipnotiza. Entonces te quedas allí nomás, te quedas para siempre y allí te recoge.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180505_mesquitaetnomatematica12.xml
<!-- 

@article{mesquita:etnomatematica:12,
author={Mesquita, Erika},
title={Alguns conhecimientos de etnomatem\'{a}tica Ashaninka},
year={2012},
}

-->
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="1">
        <sentence lang="cpb">Hiyetayiri ẽẽtsite ikatsiawayta ãtamiki.</sentence>
        <sentence lang="pt">Ensinando o filho como caçar na mata.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2">
        <sentence lang="cpb">Hiyetayiri ẽẽtsite tsika onitsi kaniri, pariãtsi</sentence>
        <sentence lang="pt">Ensinando para os filhos como trabalhar, escolher um local melhor ser rozado para plantar marcareira, banana, etc. </sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_homapani.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <!-- 
    
a   ã
e   ẽ
i   ĩ
o   õ


A   Ã
E   Ẽ
I   Ĩ
O   Õ

    
(Este hombre tenía otra casa que estaba un poco lejos en un cerro. Para llegar allí el había hecho un puente de un palo
para cruzar el precipicio, Siempre cruzaba por allí,)

(Tema irica ashéninca ari osaiquiya ipancopero intatsiqueronta. 

Ari itovirori quetziroini antaro jirivatziqui cameetha opavitapaaca
tsica impeetatzi, ari opareencaatzi ñaa otaapiqui. Ariya
iquenapiintzi ashéninca ipampyaatzi iriyaatantyaari pashinequi ipanco.)
    
    
    -->
    <text id="0">
        <sentence lang="cpb">Iyotãtawori Sokãri Ashaninka</sentence>
        <sentence lang="pt">nascimento do Sokãri</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


iyotãtawori	[=iyot][VRoot][=to.know (ES: saber); to.understand (ES: entender)][--][-anta][Asp][+APPL.REAS][=in.order.to]anta[--][-vo+n.m.][NS][+NMZ]vo[--][-ri+m.][NS][+NMZ]

sõkari	[=sõkari+n.m.+voc.][NRoot][=panpipe(s) (flute-like.instr.; ES: antara; PT: flauta); Ashéninka.flute]

ashaninka	[a-][NPers][1PL.poss+][--][=shani][VRoot][=to.be.of.the.same.group][--][-nka][NS][+NMZ.QLTY]nka

</morphology>
        <parsing/>
    </text>
    <text id="1">
        <sentence lang="cpb">Ikãta pairane Ashaninka iyotãtawori .,</sentence>
        <sentence lang="pt">Conta a história de como antigamente os Ashaninka aprenderam a tocar Sõkari.</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


ikãta	[i-][VPers][3m.S/A+][--][=kãt][VRoot][=to.say; to.call;; to.do; to.happen;; to.be (ES: ser); to.be.able][--][-a][+REAL]a

pairane	[=pairane][AdvRoot][=since; before; long.ago]

ashaninka	[a-][NPers][1PL.poss+][--][=shani][VRoot][=to.be.of.the.same.group][--][-nka][NS][+NMZ.QLTY]nka

iyotãtawori	[=iyot][VRoot][=to.know (ES: saber); to.understand (ES: entender)][--][-ant][Asp][+APPL.REAS][=in.order.to, so.that]ant[--][-a][+REAL.RFL]a[--][=vo][+3n.m.O][--][=ri][NS][+REL]

,	,[$.]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2">
        <sentence lang="cpb">oya-atxawo oimi. Ketsiroini ikamake, itsitokaitakiri. Itsitokakéri owayiri,</sentence>
        <sentence lang="pt">A mulher foi em busca de seu marido desaparecido, morto pelos guerreiros. </sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


???

oimi	[o-][NPers][3n.m.poss+][--][=imi+m.+voc.][NRoot][=husband (kin.of.a.female; ES: esposo)]

.	.[$.]

ketsiroini	[=ketsiroini][AdvRoot][=sth.from.the.beginning, first(ly) (ES: primario, originario,, primeramente)]

ikamake	[i-][VPers][3m.S/A+][--][=kam][VRoot][=to.die][--][-ak][ASP][+PRF]ak[--][-e][+IRR]e

,	,[$.]

itsitokaitakiri	[i-][VPers][3m.S/A+][--][=tsitok][VRoot][=to.crush.sth. (ES: chancar); to.kill (ES: matar)][--][-a][+EP]a[--][-it][Asp][+ANT][=past/non-past.action:before]it[--][-ak][ASP][+PRF]ak[--][-i][+IRR]i[--][=ri][+3m.O]

.	.[$.]

itsitokakéri	[i-][VPers][3m.S/A+][--][=tsitok][VRoot][=to.crush.sth. (ES: chancar); to.kill (ES: matar)][--][-ak][ASP][+PRF]ak[--][-e][+IRR]e[--][=ri][+3m.O]

owayiri	[=ovayiri+m.][NRoot][=guerrilla; warrior (ES: guerrero); murderer]

,	,[$.]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="3">
        <sentence lang="cpb">okãta iina osaykanake otsipatari mawa entsite.</sentence>
        <sentence lang="pt">Ela se sentiu só, com seus dois filhos,</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


okãta	[=okanta][ConnRoot][=so.that]

iina	[i-][NPers][3m.poss+][--][=ina+n.m.+inal@tsi.+voc.][NRoot][=mother; wife (kin.of.a.fe/male)]

osaykanake	[o-][VPers][3n.m.S/A+][--][=saik][VRoot][=to.be, to.be.at, to.be.in; to.sit; to.live][--][-an+source][ADV][+DIR][=(upon).leaving/departing;INCH:beginning.of.a.new.state;INCEP:beginning.of.a.new.action]an[--][-ak][ASP][+PRF]ak[--][-e][+IRR]e

otsipatari	[o-][VPers][3n.m.S/A+][--][=tsipat][VRoot][=to.accompany; to.join; to.combine (ES: combinar)][--][-a][+IRR]a[--][=ri][+3m.O]

mawa	[=mava][NumeralPRQ][=three]

entsite	[=entsi+n./m.+poss@te.][NRoot][=child (ES: niño)][--][-i^te][+CL:anim.PL][=animate,plural]te

.	.[$.]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="4">
        <sentence lang="cpb">Irohatsita paata ôya-atawori oimi, etakotawo enyiir owashiriwayta apaniroyni. Iroha-ããtanakawori henoke: ipeyari oowiro.</sentence>
        <sentence lang="pt">e ficou pensando num jeito de ir em busca do marido. Foi quando apareceu um ser muito poderoso, dos tempos passados, e encontrou a mulher muito triste e sozinha em seu desespêro. Então, esse ser antigo se transformou em Oowiro (gavião muito grande),</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="5">
        <sentence lang="cpb">Irohatsita oyatakariri Pitsitsiro,</sentence>
        <sentence lang="pt">e ela foi levada em suas asas até seu marido. Lá no alto, ela encontrou Pitsitsiro (outro mundo das pessoas que passam pela Terra) e também seu marido.</sentence>
        <morphology/>
    </text>
    <text id="6">
        <sentence lang="cpb">iyotakero piratãtsi, Sõkari eehatsi tãpo.</sentence>
        <sentence lang="pt">Lá ensinaram a ela o Pirãtãtsi (músicas que fazem lembrar o passado e trazem alegrias e tristezas) e a tocar o sõkari (flauta) e o tãpo (tambor).</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


iyotakero	[=iyotak][VRoot][=to.teach (ES: enseñar)][--][-e][+REAL]e[--][=ro][+3n.m.O]

???

,	,[$.]

sõkari	[=sõkari+n.m.+voc.][NRoot][=panpipe(s) (flute-like.instr.; ES: antara; PT: flauta); Ashéninka.flute]

eehatsi	[=eehatsi][ConnRoot][=also; and (PT: e)]

tãpo	[=tãpo/tambor][NRootEs][=tambor]



</morphology>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="7">
        <sentence lang="cpb">Are okãta pairane kenkitharentsi. Professor Komãyari Ashaninka do Rio Amônea - Comunidade Apiwtxa</sentence>
        <sentence lang=""/>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="8">
        <sentence lang="cpb">

Oimoshirinkikari Iwathaki Irirori

Irirori sherepiyari iyniiri osheki inintane,
aririka iranay iyamãpite. Iyeneri Itxokitsite
Ikemita inpokiromay, Thonkiri, Txoma, Txowãtsi,
eehatsi, kasheekari. Mawoyni sherepiyari ãtawiyare
tsimatsi inintane, iitarika ikowori irirori inintakoteri.

Professor Komãyari Ashaninka do Rio Amônea - Comunidade Apiwtxa
</sentence>
        <sentence lang="pt">

Protetor da matéria e dos espíritos

Ele, Sheripiyari (pajé), consegue ver muitas coisas boas através da música 
que traz as visões mostrando plantas medicinais e os caminhos do mal e do bem.
Quando bebe Kamarãpe (Ayuaska), vê o impokiromai (estrela que tem mistérios
e orienta o pajé), o Thõkiri (beija-flor), o Thowa (japó, pássaro-guia do pajé) e o 
Kashekari (onça com a qual caminha o espírito do pajé), buscando conhecimiento 
e cuidando de sua família, protegendo-a do mal. Todos os Sheripiyari e Ãtawiyari (pajé
iniciante) têm seu protetor. O que ele quiser 
fazer, ele consegue. Faz para ajudar nas curas das doenças e outras coisas mais.
</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="">
        <sentence lang="cpb">Ashi osarẽtsipaiteki</sentence>
        <sentence lang="pt">No Tempo do Verão</sentence>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


ashi	[=ashi][PrnPoss][+3SG.n.m.][=her, hers, its (ES: suyo.(de.mujer)]

osarẽtsipaiteki	[=osarentsi+m.+poss@te.][NRoot][=year (ES: año); dry.season/summer (ES: verano)][--][-paite][+ADV][=during, at.the.time.of.sth., period][--][-ki][Cas][+LOC_LOC.T]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="">
        <sentence lang="cpb">Sãkinate 5 owayro (lixo) amashitsirori kipatsi  </sentence>
        <sentence lang=""/>
        <morphology format="ashaninkamorph" analysislevel="not-fully">


owayro	[o-][NPers][3n.m.poss+][--][=vairo+n.m.+inal@ntsi.][NRoot][=name (ES: nombre)]

amashitsirori	[=amashi][VRoot][=to.wound; to.destroy (ES: malograr)][--][-ts][+EP]ts[--][-i][+IRR]i[--][=ro][+3n.m.O][--][=ri][NS][+REL]

</morphology>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180307_minagrihidrico13.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="0">
        <sentence lang="prq">Ñaantsi ashitari Nijasato (Nº 29338)</sentence>
        <sentence lang="es">Ley de Recursos Hídricos (Nº 29338)</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1">
        <sentence lang="prq">“[…] El gobierno hace eco de la alerta mundial sobre el cambio climático y se compromete a fortalecer la regulación y dedicarse con seriedad a las labores de preservación de nuestra biodiversidad, del recurso hídrico y de los glaciares”.</sentence>
        <sentence lang="es">“[…] Anampitsiteki ora ipaematanakero okanta aninkate aisati ibetsikanakero akotajero akante iroperote aminero antabaerenti amabentakotyaro aisati otimera aminakotirori, ora ashitari nijasato aisati shakarapaye”.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180428_almonacid2minedu15.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="1.0">
        <sentence lang="prq">Sheripiari aisati oaratanta</sentence>
        <sentence lang="es">El curandero y el sapito</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.1">
        <sentence lang="prq">Chora perani sheripiari ijatake anta kanojakinta ikenabeti.</sentence>
        <sentence lang="es">Cierta vez, un curandero se fue muy lejos, al fondo del bosque para cazar.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.2">
        <sentence lang="prq">Ineakeri osheto,</sentence>
        <sentence lang="es">Cuando divisó un maquisapa,</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.3">
        <sentence lang="prq">ikentakeri ¡tsekik…!</sentence>
        <sentence lang="es">lo picó con su flecha ¡tsak…!</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.4">
        <sentence lang="prq">yaanakeri,</sentence>
        <sentence lang="es">y se lo llevó,</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.5">
        <sentence lang="prq">ari abakeri antyaro inkani,</sentence>
        <sentence lang="es">entonces comenzó a llover muy fuerte.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.6">
        <sentence lang="prq">yaitaparo kamonashi, kompiroshi yobatikakotakero inkani, intsititantyari.</sentence>
        <sentence lang="es">Rápidamente el curandero cortó hojas de yarina para construir una ramadita y protegerse de la lluvia.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.7">
        <sentence lang="prq">


Meka ipokashitakeri masherotatsiri yora oratanta,
ipitiankapaka, yamenakeri sheripiari, yaitaro ibocharote yatsotakero,
ikantake: noñantabakerita yoka oaratanta, nontiritabakerita
nobocharote ityokiki, nonkajentakotantyariri. Ineabakerikea
yashaninkatanake. 

</sentence>
        <sentence lang="es">


De pronto llegó un sapito bien raro, y el curandero empezó a burlarse
sin saber que era el diablo. 

El curandero sacó de su morral su tabaco
que estaba lleno en su capiro (especie de bambú), chupó un poco y
luego le frotó en la rabadilla y las ancas del sapito, y de pronto éste
comenzó a convertirse en persona.

</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.8">
        <sentence lang="prq">Sheripiari ipeanaka tsonkiri yarasanotanake,</sentence>
        <sentence lang="es">El curandero rápidamente se convirtió en un picaflor.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.9">
        <sentence lang="prq">ikoabeta irayerime inkarajerime yoka, oaratanta ikamaritanake, te irayeriji.</sentence>
        <sentence lang="es">El sapito diablo comenzó a seguirle para fracturarle sus huesos, pero no lo alcanzó.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>
