=== hinantin/AshaninkaLexicon/treebanks/parallel_texts.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.1">
    <xs:simpleType name="language">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prq">
                <xs:annotation>
                    <xs:documentation>
                        ES: Asheninka del Peren√©.
                        EN: Perene Asheninka
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="cni"/>
            <xs:enumeration value="es"/>
            <xs:enumeration value="en"/>
            <xs:enumeration value="pt"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="parallel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="text" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sentence" minOccurs="2" maxOccurs="6">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="language" name="lang" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <!-- 
                            <xs:element name="prq" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="es" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="en" minOccurs="1" maxOccurs="1"/>
                            -->
                            <xs:element name="morphology" minOccurs="1" maxOccurs="1" nillable="false">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="parsing" minOccurs="1" maxOccurs="1" nillable="false">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180505_apiwtxagestao07.xml
<!-- 

@article{apiwtxa:gestao:07,
author={Associa\c{c}\~{a}o, Apiwtxa},
title={Plano de gest\~{a}o territorial e ambiental da terra ind\'{i}gena Kampa do rio Am\^{o}nia},
year={2007},
}

a   ã
e   ẽ
i   ĩ
o   õ

A   Ã
E   Ẽ
I   Ĩ
O   Õ

-->
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="0">
        <!-- AYAWÕTATSIRO HIYATENE AASHI IPATSITE ASHENIKA AMOYSATSI -->
        <sentence lang="cpb">AYAWÕTATSIRO HIYATENE AASHI IPATSITE ASHENĨKA AMOYSATSI</sentence>
        <sentence lang="pt">TERRA INDÍGENA KAMPA DO RIO AMÔNIA</sentence>
    </text>
    <text id="1">
        <sentence lang="cpb">ASHE AMINÃTXARI AIPATSITE ASHANINKA EERO ITHÕKATXARI ASHE. AAKA SEYKAYETSIRI ÃTAMIKI EEHATISITA AASHE WIRAKOTXA SEYKAYETSIRI OKOWAKINE AIPATSITE</sentence>
        <sentence lang="pt">PLANO DE GESTÃO TERRITORIAL E AMBIENTAL DA TERRA INDÍGENA KAMPA DO RIO AMÔNIA</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="2">
        <sentence lang="cpb">I –SEYKAYETSIRI ÃTAMIKI</sentence>
        <sentence lang="pt">I – RECURSOS FLORESTAIS E FLORÍSTICOS</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="3">
        <sentence lang="cpb">1 - Tsiirotsiiki:</sentence>
        <sentence lang="pt">1 - Murmuru:</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="4">
        <sentence lang="cpb">Akoyiteri tsiirotsiiki ashi opimãtxaa: apaa akoyiteri seikatsiri othapiyaki hiyatene eehatsii ãtawa, okakini anãpi awotsiki.</sentence>
        <sentence lang="pt">A coleta para a venda deve usar os indivíduos localizados nas margens dos rios e nos caminhos próximos das casas de moradias.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="5">
        <sentence lang="cpb">Aririka akoyiteri tsiirotsiiki othapiyaki hiyatene, ãtawaki eero athõkiri mawoyni otsiimatxe ookere apawopayni ashi royari tsimeri-payni.</sentence>
        <sentence lang="pt">Quando fizer a coleta nas margens dos rios, procurar deixar sempre alguns murmurus para as caças se alimentarem.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>

=== hinantin/AshaninkaLexicon/treebanks/parallel_texts_20180624_mihastransformador11.xml
<parallel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parallel_texts.xsd">
    <text id="1.0">
        <sentence lang="prq">IKANTAKOTA  ITSIMANTAKARI  NAVIRIRI</sentence>
        <sentence lang="es">HISTORIA  NACIMIENTO DEL HOMBRE TRANSFORMADOR</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
    <text id="1.1">
        <sentence lang="prq">Iroñaaka  itsimantakari iyora naviriri, tsimatsi aparoni shirampari pairani.</sentence>
        <sentence lang="es">Ahora,  para que acontezca el nacimiento del transformador  o convertidor de personas, había un hombre paisano antes.</sentence>
        <morphology format="" analysislevel=""/>
        <parsing format="" analysislevel=""/>
    </text>
</parallel>
